import turtle
t = turtle.Turtle()

def rectangle(color):
    t.fillcolor(color)
    t.begin_fill()
    for i in range(0, 2, 1):
        t.forward(300)
        t.right(90)
        t.forward(80)
        t.right(90)
    t.end_fill()

t.speed(3)
t.penup()
t.goto(-150, -250)
t.pendown()
t.left(90)
t.forward(400)
t.right(90)
rectangle("orange")
t.right(90)
t.forward(80)
t.left(90)
rectangle("white")
t.right(90)
t.forward(80)
t.left(90)
rectangle("green")
t.penup()
t.goto(0, 10)
t.pendown()
t.fillcolor("blue")
t.begin_fill()
t.circle(15)
t.end_fill()
#t.penup()
#t.goto(0, 25)
#t.pendown()
t.speed(0)
t.pencolor("blue")
t.pensize(5)
for i in range(0, 18, 1):
    t.right(90)
    t.forward(15)
    t.right(180)
    t.penup()
    t.forward(15)
    t.right(90)
    t.circle(15, 20)
    t.pendown()
t.speed(3)
t.penup()
t.right(90)
t.forward(15)
t.left(90)
t.pendown()
t.circle(30)
t.penup()
t.goto(400, 400)
turtle.done()
